SUPABASE_URL = "https://grrzynuhnxvcgamhossf.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdycnp5bnVobnh2Y2dhbWhvc3NmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg3NTU4OTAsImV4cCI6MjEwNDMzMTg5MH0.YDKxtHzG_CBp0lUuiTxZRMMfFYh4lCt1Thsk_QebbTU"
